### PR TITLE
fix(spaces): show correct survey type in Excel export for final polls

### LINKED ISSUE #1403: [Space] final 조사의 경우에도 응답 분석 내 엑셀 다운로드 시 조사 구분에 사전 조사라 뜨고 있음.
**Describe the bug**
final 조사의 경우에도 응답 분석 내 엑셀 다운로드 시 조사 구분에 사전 조사라 뜨고 있음.

**Testing environment or URL**
- OS: Mac OS
- Browser/Device: Web
- URL (if applicable):

**To Reproduce**
1. 스페이스 페이지 접속
2. 응답 생성 후 Creator 화면에서 응답 분석 페이지 접속
3. 응답 분석 페이지 내 엑셀 다운로드 클릭

**Screenshots or Videos**
Image

**Expected result**
사전 조사가 아닐 때는 조사 구분을 최종 설문으로 수정이 되어야 함.

### PR DESCRIPTION
**Pull request by doyooon**
[poll-analysis (1).xlsx](https://github.com/user-attachments/files/26500565/poll-analysis.1.xlsx)
[poll-analysis (2).xlsx](https://github.com/user-attachments/files/26500566/poll-analysis.2.xlsx)
[poll-analysis (3).xlsx](https://github.com/user-attachments/files/26500567/poll-analysis.3.xlsx)
[poll-analysis (4).xlsx](https://github.com/user-attachments/files/26500568/poll-analysis.4.xlsx)

영문, 한글 모두 반영해서 잘 나오게 변경했습니다.
close #1403

### CODE REVIEW

File: app/ratel/src/features/spaces/pages/apps/apps/analyzes/views/analyze/poll/page.rs [hunk 1]
```diff
@@ -742,6 +742,12 @@ fn build_excel_data(
         });
     }
 
+    let sample_category_label = if poll.space_action.prerequisite {
```
Comment (victor138128) [inline app/ratel/src/features/spaces/pages/apps/apps/analyzes/views/analyze/poll/page.rs]: sample_category_label 이 아니라 category_label이 되야 할거 같아요.

**Review by victor138128 — APPROVED** [review]

File: app/ratel/src/features/spaces/pages/apps/apps/analyzes/views/analyze/poll/page.rs (hunk 1 above)
Comment (doyooon) [reply app/ratel/src/features/spaces/pages/apps/apps/analyzes/views/analyze/poll/page.rs]: @victor138128 네이밍 변경하면 될까요?

Comment (doyooon) [reply app/ratel/src/features/spaces/pages/apps/apps/analyzes/views/analyze/poll/page.rs]: 넵!

File: app/ratel/src/features/spaces/pages/apps/apps/analyzes/views/analyze/poll/page.rs [hunk 2]
```diff
@@ -742,6 +742,12 @@ fn build_excel_data(
...
+        tr.sample_survey.to_string()
```
Comment (hackartists) [inline app/ratel/src/features/spaces/pages/apps/apps/analyzes/views/analyze/poll/page.rs]:
```suggestion
        tr.sample_survey.translate(&lang)
```
이런 형태가 되어야 하지 않나요?
