### PR TITLE
Fix  s3

### LINKED ISSUE #834: Post - Image Insertion Error in Post Body
**Describe the bug**
When creating a Post, an error occurs when inserting an image into the post body.

**Testing environment or URL**
- OS: Mac
- Browser/Device: Chrome
- URL (if applicable): https://dev.ratel.foundation/posts/new

**To Reproduce**
1. Go to Create Post
2. Attempt to insert an image into the post body
3. Observe that the image fails to upload / display

**Screenshots or Videos**
If applicable, add screenshots or a video to help explain your problem.

https://github.com/user-attachments/assets/fcbd8679-cefe-4409-a8d7-0039fd41e2d5

**Expected result**
What did you expect to happen?
Images should upload and display correctly in the post body

**Additional context**

### PR DESCRIPTION
**Pull request by blikq**
fix for s3 using proper region
closes #834 #761 

Screenshot from 2025-12-09 23-54-27

### CODE REVIEW

File: packages/main-api/src/utils/s3_upload.rs [hunk 1]
```diff
@@ -62,7 +62,10 @@ pub async fn get_put_object_uri(
                 Error::AssetError(e.to_string())
             })?;
         presigned_uris.push(presigned_request.uri().to_string());
-        uris.push(format!("https://{}/{}", aws_bucket_config.name, key));
+        uris.push(format!(
+            "https://{}.s3.{}.amazonaws.com/{}",
+            aws_bucket_config.name, aws_bucket_config.region, key
+        ));
```
Comment (hackartists) [inline packages/main-api/src/utils/s3_upload.rs]: I recommend that `S3Config` has `get_url()` method and use it rather than formatting whenever using them. @blikq
