### PR TITLE
Git Fixes

### LINKED ISSUE #950: [Text Fix] Membership - Korean Typo Correction ("기업를" → "기업을")
**Describe the bug**
In the Korean version of the Membership section, there is a typo in the text.
The word "기업를" is grammatically incorrect and should be corrected to "기업을".

**Testing environment or URL**
- OS: Mac
- Browser/Device: Chrome
- URL (if applicable): https://dev.ratel.foundation/membership

**To Reproduce**
1. Switch the language to Korean
2. Navigate to the Membership section
3. Locate the text containing "기업를"

**Screenshots or Videos**
If applicable, add screenshots or a video to help explain your problem.

Image

**Expected result**
What did you expect to happen?
The text should display "기업을" correctly

**Additional context**

### PR DESCRIPTION
**Pull request by blikq**
closes #950 #948 #943

### CODE REVIEW

File: ts-packages/web/src/app/(social)/threads/[id]/thread-page.tsx [hunk 1]
```diff
@@ -2,9 +2,21 @@ import { useThreadController } from './use-thread-controller';
...
 import ThreadComment from './_components/comment';
 import ThreadPost from './_components/thread';
+import { useEffect } from 'react';
+import { useLocation } from 'react-router';
 
 export default function ThreadPage() {
   const ctrl = useThreadController();
+  const location = useLocation();
+
+  useEffect(() => {
```
Comment (victor138128) [inline ts-packages/web/src/app/(social)/threads/[id]/thread-page.tsx]: @blikq 

I think there was a way to implement the feature of moving to the next page when a comment is clicked without using scrollIntoView. Is there a reason you chose to use scrollIntoView?

**Review by victor138128 — APPROVED** [review]
